<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>olympiad-quizzer-net.Core.Tests.Common</AssemblyName>
    <RootNamespace>OlympiadQuizzer.Core.Tests.Common</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <IsPackable>false</IsPackable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\olympiad-quizzer-net.Core.Domain\olympiad-quizzer-net.Core.Domain.csproj" />
  </ItemGroup>

</Project>
