<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>olympiad-quizzer-net.App.API</AssemblyName>
    <RootNamespace>OlympiadQuizzer.App.Api</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\olympiad-quizzer-net.Core.Domain\olympiad-quizzer-net.Core.Domain.csproj" />
    <ProjectReference Include="..\..\Infrastructure\olympiad-quizzer-net.Infrastructure.SQLite\olympiad-quizzer-net.Infrastructure.SQLite.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="olympiad-quizzer-net.App.API.L1" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\..\data\questions.db"
             Link="data\questions.db"
             CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
